# Generated by Django 4.2.7 on 2023-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='nid',
            field=models.IntegerField(null=True),
        ),
    ]
