# Generated by Django 4.2.7 on 2023-12-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profiledetails_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpeg', null=True, upload_to='profile_pics'),
        ),
    ]
