# Generated by Django 4.2.7 on 2023-12-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profiledetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=255, null=True, verbose_name='MartailStatus'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='martail_status',
            field=models.CharField(blank=True, choices=[('Male', 'Maried'), ('Female', 'Unmaried'), ('Other', 'Other')], max_length=255, null=True, verbose_name='MartailStatus'),
        ),
    ]
