# Generated by Django 4.2.7 on 2023-12-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profiledetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='address',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='martail_status',
            field=models.CharField(blank=True, choices=[('Maried', 'Maried'), ('Unmaried', 'Unmaried'), ('Other', 'Other')], default='Maried', max_length=255, null=True),
        ),
    ]
