# Generated by Django 4.2.7 on 2023-12-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profiledetails_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='modified',
        ),
    ]
