# Generated by Django 4.2.7 on 2023-12-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profiledetails_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledetails',
            old_name='created',
            new_name='created_at',
        ),
    ]
