# Generated by Django 4.2.7 on 2023-12-16 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_profiledetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
