# Generated by Django 4.2.7 on 2023-12-16 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_profiledetails_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
