# Generated by Django 4.2.7 on 2023-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_profiledetails_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='modified',
        ),
    ]
