# Generated by Django 4.2.7 on 2023-12-16 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_remove_profiledetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
