# Generated by Django 4.2.7 on 2023-12-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_profiledetails_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
